Добавил пример плагина облачного подписания
DirectumCompany/Sungero.Plugins.Templates pull request #3
Opened 2021-07-07 07:46 UTC by alpolin

1. Изменил в серверном плагине мультитаргет на .net standard в связи с переходом на .net core и на windows тоже.
2. Добавил абстрактный пример плагина облачного подписания

! Перед слиянием PR нужно создать ветку 4.0

2021-07-07 08:06 UTC, kmosolov commented
В ServerPlugin.targets остались condition на framework, в них больше нет смысла

2021-07-07 08:07 UTC, kmosolov requested changes
В ServerPlugin.targets остались condition на framework, в них больше нет смысла

2021-07-07 08:39 UTC, alpolin commented
> В ServerPlugin.targets остались condition на framework, в них больше нет смысла

Убрал

2021-07-08 05:05 UTC, kmosolov approved these changes

2021-07-08 05:05 UTC, merged